### PR TITLE
Refactoring of the build definitions (including Maven, test executions and Travis CI)

### PR DESCRIPTION
**Pull request by thomaskrause**
The current build definitions have the following problems that make it difficult to setup a proper Atomic developer instance:

1. Maven and Eclipse target platform definition differ: it is possible that the maven build works but the Eclipse one not (or shows errors)
2. The used p2 update sites sometimes have duplicate content and it's not clear which dependency is located in which repository (the Eclipse editor won't help here much as well since it seems to be broken a lot of times especially for large repositories)
3. An extra logging project which is just a copy of Log4j 2
4. Test execution and Travis CI won't work 

This PR addresses the first two issues by using a simple target definition file format/plugin (https://github.com/mbarbero/fr.obeo.releng.targetplatform) which can be easily converted to an actual Eclipse target definition file and by configuring Maven to using the explicit target definition file.

The other issues are addressed by some cleanup and refactoring. I removed the one test project that did not have any tests yet in favour of the one GUI integration test project and unit test directly inside each plugin. If needed a new test plugin can be added later, but now we have a state where Travis CI works and it's easier to review pull requests since there is a working state.

### CODE REVIEW

**Comment by thomaskrause** [comment]
I updated the PR to also not include an extra loggings project any longer but to use the "extra.library" feature of PDE.

**Comment by thomaskrause** [comment]
Ok, I updated the PR a little bit more to make sure that Maven builds, tests and CI for pull requests work out of the box (hopefully). This should make it easier to review future changes.

**Comment by sdruskat** [comment]
Actually, the `.logging` plugin is necessary, otherwise Log4j 2 isn't usable from within the OSGi platform asynchronously, cf. [this blog post](http://blog.sdruskat.net/log4j2-in-eclipse-rcp-with-async-loggers/).

This PR builds, but logging will not work.

**Review by sdruskat — APPROVED** [review]

**Review by sdruskat — CHANGES_REQUESTED** [review]
This won't work. The logging plugin is needed the way it is for async logging with Log4j 2 in OSGi to work (cf. comment in PR).

**Review by sdruskat — CHANGES_REQUESTED** [review]
In an Eclipse RCP, the tests are supposed to be in fragments, not the main plugins (cf. [here](http://www.vogella.com/tutorials/EclipseFragmentProject/article.html#typical-use-cases-for-fragments), hence, please leave where they are.

**Review by sdruskat — CHANGES_REQUESTED** [review]
Setting up logging (async) within an Eclipse RCP is intricate, hence the Log4j2 jars were extracted into a plugin to make it work. Please roll back.

**Review by sdruskat — CHANGES_REQUESTED** [review]
See above.

**Review by sdruskat — CHANGES_REQUESTED** [review]
See above.

**Review by sdruskat — CHANGES_REQUESTED** [review]
See above.

**Comment by sdruskat** [comment]
Thanks a lot for the PR! Should definitely switch to the new target definition files.
However, the logging plugin must stay where it is, and the tests should remain within fragments (for releng reasons).
Let's discuss how we should move forward with this (manual transfer of wanted changes or cherry-picking).

**Comment by sdruskat** [comment]
Cherry-picked this PR, thanks.
Ignored commits:
9bb048de14bd2fb482090dc5b4861c09dd6fe248
54a1f846c79f5c84d5820456ae025394cc80d1d9
60a3017b3981b73152b7f35eb2acc9a9820c4517
5c8a9f0060de7d7e28b5eb2a3109cb4270b3e72f
33b855a953b530013583e8bb3cc23d788607bb04
4c55852cadda6b961f05e4e40ec036625dc7c1ef

**Pull request closed without merging**
